### ISSUE TITLE
Ranged addresses w/ children rows don't return in block search response

### ISSUE THREAD

**Issue by Alexander-M-Waldman** [CityOfPhiladelphia/ais#67]
Address summary has rows for these 3 addresses: 949-51 N LAWRENCE ST, 951 N LAWRENCE ST, 949 N LAWRENCE ST.  
The address link table lists 949 and 951 Lawrence St is as “in range” of 949-51 N Lawrence St, but does not have an entry for the ranged address version (949-51). 
Block search uses exclude_children fct to filter out addresses with address_link relationship=”in range”.  (This happens for other addresses having this relationship as well)
This ranged address (949-51) also doesn’t have an OPA account #, so none of these show up in the block search response.

**Comment by rbrtmrtn** [comment]
It sounds like `exclude_children` is catching too much here. I think it was intended to filter out children that looked like artifacts of the range-splitting process, but I'm wondering if we really want to do that because a) they could still have meaningful/unique data attached to them and b) the `opa_only` filter will weed them out in Property anyway. What do you think about commenting out [this line](https://github.com/CityOfPhiladelphia/ais/blob/master/ais/api/views.py#L197) @Alexander-M-Waldman ?

**Comment by rbrtmrtn** [comment]
Actually that's not going to work because the children have OPA #'s and will still be let in by `opa_only`. I think `exclude_non_opa` has to be reworked to use the `match_type` field from `address_property`. It should only let in addresses where `match_type = 'exact'`. Hopefully the join won't be too much of a performance issue, and if it is we can just add that field to `address_summary`.

**Comment by rbrtmrtn** [comment]
See #48.

**Comment by Alexander-M-Waldman** [comment]
#Closed by c5071a46d48b369fdc55aa0fb096127f7906be9d
